
export const SHOW_KEYBOARD = "SHOW_KEYBOARD";
export const HIDE_KEYBOARD = "HIDE_KEYBOARD";
export const LOGGED_IN = "LOGGED_IN";
export const LOGGING_IN = "LOGGING_IN";
export const SCREEN_LOADING = "SCREEN_LOADING";

export const SET_PROJECTS = "SET_PROJECTS"
export const SET_SELECTED_PROJECT = "SET_SELECTED_PROJECT"
export const SET_LAST_ADDED_PROJECT = "SET_LAST_ADDED_PROJECT"
export const DELETE_PROJECT = "DELETE_PROJECT"

export const SET_SPRINTS = "SET_SPRINTS"
export const SET_LAST_ADDED_SPRINT = "SET_LAST_ADDED_SPRINT"

export const SET_TASKS = "SET_TASKS"
export const SET_SELECTED_TASK = "SET_SELECTED_TASK"
export const SET_LAST_ADDED_TASK = "SET_LAST_ADDED_TASK"
export const SET_MYTASK = "SET_MYTASK"
export const SET_TASK_DETAILS = "SET_TASK_DETAILS"
export const SET_TASK_STATUS_FILTER = "SET_TASK_STATUS_FILTER"